### ISSUE TITLE
Timeout for certain counties?

### ISSUE THREAD

**Issue by jeffcsauer** [wpinvestigative/arcos#2]
Hi all, 

when using `county_raw()`, some counties appear to time out and report a HTTP error 502. Can any others replicate on their machines? I can provide a list of all the counties where this appears to be an issue. 

Example:
`library(arcos)`
`test = county_raw(county="King", state="WA", key="WaPo")`

This occurs for about 200 counties.

Edit: another quick example with LA: 

`> test = county_raw(county = "los angeles", state = "CA", key = "WaPo")`
`Error in open.connection(con, "rb") : HTTP error 504.`
`> test = county_raw(county = "LosAngeles", state = "CA", key = "WaPo")`
`Error in open.connection(con, "rb") : HTTP error 502.`
`> test = county_raw(county = "Los Angeles", state = "CA", key = "WaPo")`
`Error in open.connection(con, "rb") : HTTP error 504. `

**Comment by andrewbtran** [comment]
Thanks for letting us know. We're looking into bumping up the timeout limit to accommodate huge files like those counties.

**Comment by jeffcsauer** [comment]
Hi @andrewbtran - any update on this? Still getting an HTTP error 502 when using `county_raw()` on LA. Do you think it would be better to just handle the raw data for the time being?

**Comment by andrewbtran** [comment]
Finally fixed. The original API has been updated to return a csv link instead of presenting as json. It required [changing](https://github.com/wpinvestigative/arcos/blob/ce156dcf970062700f9f74d7e2c84c998f75dfa6/R/raw.R#L42) the ARCOS R package function to read in as a csv with vroom instead of reading in as a json file. The dev version has been updated. Will push to CRAN next week.

**Comment by jeffcsauer** [comment]
Thanks so much, @andrewbtran! This is so great!!!

**Comment by jeffcsauer** [comment]
Can confirm, counties like Los Angeles are now successfully downloading!
